assignment/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('content.urls')),
    url(r'^admin/', admin.site.urls),
]

content/urls.py
from django.conf.urls import url

from . import views

app_name = 'content'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<page_number>[0-9]+)/', views.IndexView.as_view(), name='index_page'),
    url(r'task/(?P<pk>[0-9]+)/', views.TaskView.as_view(), name='task')
]

hello/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'task/(?P<task_number>[0-9]+)/details/$', views.tasks, name="tasks"),
]

content/models.py
from django.db import models

class Users(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    master = models.BooleanField()
    
    def __str__(self):
        return self.name

class Tasks(models.Model):
    task_name = models.CharField(max_length=200)
    estimated_time = models.DurationField()
    value = models.DecimalField(max_digits=10, decimal_places=2)
    deadline = models.DateTimeField()
    master = models.ForeignKey('Users', on_delete=models.CASCADE, 
                                related_name = "master_user")
    slave = models.ForeignKey('Users', on_delete=models.CASCADE, 
                                related_name = "slave_user")
    pub_date = models.DateTimeField()
    description = models.TextField(default="No description.")

    def __str__(self):
        return self.task_name

hello/models.py
from django.db import models

# Create your models here.

content/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponse
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Users,Tasks

class IndexView(generic.ListView):
    template_name = 'content/index.html'
    context_object_name = 'tasks_list'
    
    def __init__(self):
        self.page_size = 1

    def dispatch(self, request, *args, **kwargs):
        page_number = kwargs.get('page_number', None)
        if page_number is None:
            self.page_number = 1
        else:
            self.page_number = page_number
        try:
            ret = super(IndexView, self).dispatch(request, *args, **kwargs)
        except AttributeError:
            raise Http404
        return ret

    def get_queryset(self):
        """Return the tasks list."""
        tasks = Tasks.objects.all()
        paginator = Paginator(tasks, 1)
        try:
            queryset = paginator.page(self.page_number)
        except PageNotAnInteger:
        # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)
        return queryset

class TaskView(generic.DetailView):
    model = Tasks
    template_name = 'content/task.html'

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return HttpResponse("سلام")

def tasks(request, task_number):
    response = " کار شماره" + task_number 
    return HttpResponse(response)

content/templates/content/index.html
{% extends "base.html" %}

{% load static %}

{% block css_links %}
    <link rel="stylesheet" href="{% static "content/index.css" %}" />
{% endblock %}

{% block content %}
    <div class="ui middle aligned center aligned grid">
      <div class="column">
        <h2 class="ui teal header">لیست کارها</h2>
        <table class="ui inverted teal center aligned table">
            <thead>
                <tr>
                    <th>عنوان کار</th>
                    <th>ارزش کار</th> 
                    <th>تخمین زمانی</th>
                    <th>صاحب کار</th>
                    <th>توضیحات</th>
                </tr>
            </thead>
            <tbody>
              {% for task in tasks_list %}
                <tr>
                    <td> {{task.task_name}} </td>
                    <td> {{task.value}} </td>
                    <td> {{task.estimated_time}} </td>
                    <td> {{task.master.name}} </td>
                    <td>
                        <a class="ui inverted black basic button" href="{% url "content:task" task.pk %}">توضیحات</a> 
                    </td>
                </tr>
              {% endfor %}
            </tbody>
        </table>
        <div class="ui right floated pagination menu">
              {%if tasks_list.has_previous %}
                <a class = "icon item" href="{% url "content:index_page" tasks_list.previous_page_number %}">صفحه قبل</a>
              {% endif %}
              {%if tasks_list.has_next%}
                <a class = "icon item" href="{% url "content:index_page" tasks_list.next_page_number %}">صفحه بعد</a>
              {% endif %}
        </div>
      </div>
    </div>
    
{% endblock %}

content/templates/content/task.html
{% extends "base.html" %}

{% load static %}

{% block css_links %}
    <link rel="stylesheet" href="{% static "content/index.css" %}" />
{% endblock %}

{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui teal header">{{tasks.task_name}}</h2>
        <table class="ui inverted teal center aligned table">
            <thead>
                <tr>
                    <th>تخمین زمانی</th>
                    <th>ارزش کار</th> 
                    <th>افزوده شده در</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td> {{tasks.estimated_time}} </td>
                    <td> {{tasks.value}} </td>
                    <td> {{tasks.pub_date}} </td>
                </tr>
            </tbody>
        </table>
        <h4 class="ui teal header">توضیحات</h4>
        <p> {{tasks.description}} </p>
    </div>
</div>
{% endblock %}

templates/base.html
<!doctype html>

<html dir="rtl">
    <head>
    <meta charset="utf-8"/>
    <title>
      {% block title %}
        سامانه انجام کار
      {% endblock %}
    </title>

    <link
      rel="stylesheet"
      href="https://cdn.rtlcss.com/semantic-ui/2.2.6/semantic.rtl.css">

    {% block css_links %}
    {% endblock %}

    <style type="text/css">
     body {
       background-color: #DADADA;
     }

     .ui.menu {
       border-radius: 0;
       margin: 0;
     }

     @media (min-height: 320px) {
      .ui.footer.form-page { 
        position: absolute;
        bottom: 0;
        width: 100%;
        }
    }
    </style>
  </head>

  <body>
    <div class="menu-container">
      <div class="ui large menu">
        <div class="ui main container">
          <a class="header item" href="{% url "content:index" %}">
            سامانه انجام کار
          </a>
        </div>
      </div>

    {% block content %}
    {% endblock %}
    
  </div>

    <div class="ui inverted vertical footer segment form-page">
    <div class="ui container">
        <div class="ui inverted horizontal link list">
            <a href="cafebazaar.ir" class="item"> درباره ما </a>
            <a href="Divar.ir" class="item"> قوانین </a>
        </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous">
    </script>
    <script src="https://cdn.rtlcss.com/semantic-ui/2.2.6/semantic.min.js">
    </script>

    {% block js_scripts %}
    {% endblock %}
  </body>
</html>